In [1]:
from scipy.sparse import csr_matrix
import numpy as np

In [2]:
a = csr_matrix(np.eye(20000, 20000))

In [3]:
b = csr_matrix(1/np.matrix(np.random.randn(20000)))

In [4]:
c  = a.multiply(b)

In [5]:
c.toarray()

array([[-0.88995829,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.56043077,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.8191119 , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.90816456,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -1.87561858,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.49364493]])

In [6]:
b.toarray()

array([[-0.88995829,  0.56043077,  0.8191119 , ...,  0.90816456,
        -1.87561858,  0.49364493]])

In [7]:
d  = a.T.multiply(b)

In [8]:
d.toarray()

array([[-0.88995829,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.56043077,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.8191119 , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.90816456,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -1.87561858,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.49364493]])

In [9]:
(d*2).toarray()

array([[-1.77991659,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.12086154,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.63822379, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  1.81632911,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -3.75123716,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.98728986]])

In [25]:
confidence = csr_matrix([[8,2,2],[4,10,6],[7,2,9]])
lift = csr_matrix([[11,22,33],[44,55,66],[77,88,99]])

In [26]:
confidence.

SyntaxError: invalid syntax (<ipython-input-26-513f0372cca1>, line 1)

In [27]:
lift[confidence<=5]=0

/Users/kenji_tachibana/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/scipy/sparse/compressed.py:274: SparseEfficiencyWarning: Comparing a sparse matrix with a scalar greater than zero using <= is inefficient, try using > instead.
  warn(bad_scalar_msg, SparseEfficiencyWarning)


In [28]:
lift.toarray()

array([[11,  0,  0],
       [ 0, 55, 66],
       [77,  0, 99]], dtype=int64)