In [39]:
from scipy.sparse import csr_matrix
import numpy as np

In [40]:
a = csr_matrix(np.eye(20000, 20000))

In [41]:
b = csr_matrix(1/np.matrix(np.random.randn(20000)))

In [42]:
c  = a.multiply(b)

In [ ]:
c.toarray()

In [27]:
b.toarray()

array([[ 2.58050186,  1.76158225, -0.57404945, ...,  0.59376915,
         1.15451663,  1.81306552]])

In [28]:
d  = a.T.multiply(b)

In [43]:
d.toarray()

array([[ 2.58050186,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.76158225,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.57404945, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.59376915,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.15451663,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.81306552]])

In [48]:
(d*2).toarray()

array([[ 5.16100371,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  3.5231645 ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.1480989 , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  1.1875383 ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         2.30903326,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  3.62613104]])